project_id = "iosceukdfokpptvqfirp"

[functions.ai-grading-assistant]
verify_jwt = false

[functions.ai-image-generator]
verify_jwt = false

[functions.ai-knowledge-base]
verify_jwt = false

[functions.ai-meeting-assistant]
verify_jwt = false

[functions.ai-school-assistant]
verify_jwt = false

[functions.ai-system-admin]
verify_jwt = false

[functions.ai-timetable-generator]
verify_jwt = false

[functions.enhanced-ai-grading]
verify_jwt = false

[functions.enhanced-knowledge-base]
verify_jwt = false

[functions.generate-lesson-recap]
verify_jwt = true

[functions.realtime-classroom]
verify_jwt = false

[functions.send-contact-request]
verify_jwt = false

[functions.send-demo-request]
verify_jwt = false

[functions.video-conference-signaling]
verify_jwt = false

[functions.ai-teaching-assistant]
verify_jwt = false

[functions.dynamic-content-generator]
verify_jwt = false

[functions.ai-voice-service]
verify_jwt = false

[functions.student-analytics-ai]
verify_jwt = false

[functions.creative-ai-features]
verify_jwt = false