-- Insert sample applications for testing
INSERT INTO public.enrollment_applications (
  student_first_name,
  student_last_name,
  student_date_of_birth,
  year_group,
  application_status,
  priority_score,
  progress_percentage,
  parent_first_name,
  parent_last_name,
  parent_email,
  parent_phone,
  address_line_1,
  city,
  postal_code,
  country,
  emergency_contact_name,
  emergency_contact_phone,
  emergency_contact_relationship,
  previous_school_name,
  previous_school_address,
  reason_for_leaving,
  academic_achievements,
  extracurricular_activities,
  special_requirements,
  medical_conditions,
  dietary_requirements,
  sen_requirements
) VALUES 
(
  'Emma',
  'Johnson',
  '2010-05-15',
  'Year 8',
  'submitted',
  85,
  25,
  'Sarah',
  'Johnson',
  'sarah.johnson@email.com',
  '+44 7123 456789',
  '123 Oak Street',
  'London',
  'SW1A 1AA',
  'United Kingdom',
  'Michael Johnson',
  '+44 7987 654321',
  'Father',
  'Riverside Primary School',
  '456 River Road, London',
  'Family relocation',
  'Top 10% in Mathematics, Science Fair Winner 2023',
  'Piano, Swimming, Drama Club',
  'None',
  'Mild asthma',
  'No special dietary requirements',
  'None'
),
(
  'James',
  'Smith',
  '2009-09-22',
  'Year 9',
  'reviewing',
  92,
  45,
  'David',
  'Smith',
  'david.smith@email.com',
  '+44 7234 567890',
  '789 High Street',
  'Manchester',
  'M1 1AA',
  'United Kingdom',
  'Lisa Smith',
  '+44 7876 543210',
  'Mother',
  'Greenfield Academy',
  '321 Green Lane, Manchester',
  'Seeking better academic opportunities',
  'National Chess Champion, Grade 8 Violin',
  'Chess Club, Orchestra, Debate Team',
  'Requires laptop for coding classes',
  'None',
  'Vegetarian',
  'Gifted and talented program'
),
(
  'Sophia',
  'Williams',
  '2011-02-10',
  'Year 7',
  'assessment',
  78,
  65,
  'Emma',
  'Williams',
  'emma.williams@email.com',
  '+44 7345 678901',
  '456 Rose Avenue',
  'Birmingham',
  'B1 1AA',
  'United Kingdom',
  'Robert Williams',
  '+44 7765 432109',
  'Father',
  'St. Mary''s Primary',
  '789 Church Street, Birmingham',
  'Completed primary education',
  'Art Competition Winner, Reading Ambassador',
  'Art Club, Library Helper, Choir',
  'Art supplies and workspace',
  'None',
  'Gluten-free diet',
  'None'
),
(
  'Oliver',
  'Brown',
  '2008-11-30',
  'Year 10',
  'interview',
  88,
  80,
  'Helen',
  'Brown',
  'helen.brown@email.com',
  '+44 7456 789012',
  '321 Elm Road',
  'Bristol',
  'BS1 1AA',
  'United Kingdom',
  'Mark Brown',
  '+44 7654 321098',
  'Father',
  'Bristol Grammar',
  '654 Grammar Road, Bristol',
  'Financial considerations',
  'GCSE Mathematics A*, Head Boy 2023',
  'Football Captain, Student Council, Coding Club',
  'Access to computer lab',
  'Type 1 Diabetes',
  'Diabetic meal plan',
  'None'
),
(
  'Lily',
  'Davis',
  '2010-07-18',
  'Year 8',
  'approved',
  95,
  100,
  'Catherine',
  'Davis',
  'catherine.davis@email.com',
  '+44 7567 890123',
  '987 Maple Close',
  'Leeds',
  'LS1 1AA',
  'United Kingdom',
  'Anthony Davis',
  '+44 7543 210987',
  'Father',
  'Leeds International School',
  '147 International Drive, Leeds',
  'Parent job relocation',
  'Trilingual (English, French, Spanish), Science Olympiad Gold',
  'Model UN, Environmental Club, Tennis',
  'Language support materials',
  'None',
  'No special dietary requirements',
  'English as additional language support'
);