-- Insert sample applications using correct pathway enum value
INSERT INTO public.enrollment_applications (
  student_name,
  date_of_birth,
  year_group,
  status,
  priority_score,
  workflow_completion_percentage,
  parent_name,
  parent_email,
  parent_phone,
  home_address,
  country,
  postal_code,
  emergency_contact_name,
  emergency_contact_phone,
  emergency_contact_relationship,
  previous_school,
  current_year_group,
  academic_notes,
  special_requirements,
  medical_information,
  school_id,
  pathway,
  application_number
) VALUES 
(
  'Emma Johnson',
  '2010-05-15',
  'Year 8',
  'submitted',
  85,
  25,
  'Sarah Johnson',
  'sarah.johnson@email.com',
  '+44 7123 456789',
  '123 Oak Street, London, SW1A 1AA',
  'United Kingdom',
  'SW1A 1AA',
  'Michael Johnson',
  '+44 7987 654321',
  'Father',
  'Riverside Primary School',
  'Year 7',
  'Top 10% in Mathematics, Science Fair Winner 2023',
  'None',
  'Mild asthma',
  (SELECT id FROM schools LIMIT 1),
  'standard_digital',
  'APP20240001'
),
(
  'James Smith',
  '2009-09-22',
  'Year 9',
  'reviewing',
  92,
  45,
  'David Smith',
  'david.smith@email.com',
  '+44 7234 567890',
  '789 High Street, Manchester, M1 1AA',
  'United Kingdom',
  'M1 1AA',
  'Lisa Smith',
  '+44 7876 543210',
  'Mother',
  'Greenfield Academy',
  'Year 8',
  'National Chess Champion, Grade 8 Violin',
  'Requires laptop for coding classes',
  'None',
  (SELECT id FROM schools LIMIT 1),
  'standard_digital',
  'APP20240002'
),
(
  'Sophia Williams',
  '2011-02-10',
  'Year 7',
  'assessment_scheduled',
  78,
  65,
  'Emma Williams',
  'emma.williams@email.com',
  '+44 7345 678901',
  '456 Rose Avenue, Birmingham, B1 1AA',
  'United Kingdom',
  'B1 1AA',
  'Robert Williams',
  '+44 7765 432109',
  'Father',
  'St. Mary''s Primary',
  'Year 6',
  'Art Competition Winner, Reading Ambassador',
  'Art supplies and workspace',
  'None',
  (SELECT id FROM schools LIMIT 1),
  'standard_digital',
  'APP20240003'
),
(
  'Oliver Brown',
  '2008-11-30',
  'Year 10',
  'interview_scheduled',
  88,
  80,
  'Helen Brown',
  'helen.brown@email.com',
  '+44 7456 789012',
  '321 Elm Road, Bristol, BS1 1AA',
  'United Kingdom',
  'BS1 1AA',
  'Mark Brown',
  '+44 7654 321098',
  'Father',
  'Bristol Grammar',
  'Year 9',
  'GCSE Mathematics A*, Head Boy 2023',
  'Access to computer lab',
  'Type 1 Diabetes',
  (SELECT id FROM schools LIMIT 1),
  'sibling_automatic',
  'APP20240004'
),
(
  'Lily Davis',
  '2010-07-18',
  'Year 8',
  'approved',
  95,
  100,
  'Catherine Davis',
  'catherine.davis@email.com',
  '+44 7567 890123',
  '987 Maple Close, Leeds, LS1 1AA',
  'United Kingdom',
  'LS1 1AA',
  'Anthony Davis',
  '+44 7543 210987',
  'Father',
  'Leeds International School',
  'Year 7',
  'Trilingual (English, French, Spanish), Science Olympiad Gold',
  'Language support materials',
  'None',
  (SELECT id FROM schools LIMIT 1),
  'internal_progression',
  'APP20240005'
);