// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iosceukdfokpptvqfirp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlvc2NldWtkZm9rcHB0dnFmaXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTU0NTAsImV4cCI6MjA2OTc5MTQ1MH0.WPkORWUMRfMEAVlkl6--r8rZ85YFXeJlXFkKya1PLuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});