import React, { useState, useEffect, useCallback } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { 
  Map, 
  Bus, 
  Users, 
  MapPin, 
  Wand2, 
  AlertTriangle, 
  CheckCircle2, 
  Clock, 
  Loader2,
  Route,
  Edit2,
  Trash2,
  Plus,
  RefreshCw,
  ListChecks
} from 'lucide-react';
import { RouteProfile, TransportTrip, TripStop, useTripPlanning } from '@/hooks/useTripPlanning';
import { useRouteOptimizer, TripSuggestion, ConflictCheck } from '@/hooks/useRouteOptimizer';
import { useTransportData } from '@/hooks/useTransportData';
import { StopAssignmentPanel } from './StopAssignmentPanel';
import { TripMapView } from './TripMapView';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

interface TripMapPlannerProps {
  routeProfile: RouteProfile;
  onBack: () => void;
}

interface StopWithStatus extends TripStop {
  colorStatus: 'red' | 'yellow' | 'green';
}

export const TripMapPlanner: React.FC<TripMapPlannerProps> = ({ routeProfile, onBack }) => {
  const { userSchoolId, vehicles, drivers } = useTransportData();
  const {
    trips,
    tripStops,
    fetchTripsForProfile,
    fetchTripStops,
    addTrip,
    updateTrip,
    deleteTrip,
    addTripStop,
    updateTripStop,
    deleteTripStop,
  } = useTripPlanning(userSchoolId);

  const {
    isGenerating,
    generatedTrips,
    autoGenerateTrips,
    checkResourceConflicts,
    createTripsFromSuggestions,
    setGeneratedTrips,
  } = useRouteOptimizer();

  const [profileTrips, setProfileTrips] = useState<TransportTrip[]>([]);
  const [selectedTrip, setSelectedTrip] = useState<TransportTrip | null>(null);
  const [selectedTripStops, setSelectedTripStops] = useState<StopWithStatus[]>([]);
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false);
  const [showEditTripDialog, setShowEditTripDialog] = useState(false);
  const [vehicleCapacity, setVehicleCapacity] = useState(40);
  const [optimizationMode, setOptimizationMode] = useState<'distance' | 'time' | 'balanced'>('distance');
  const [loading, setLoading] = useState(true);
  const [conflict, setConflict] = useState<ConflictCheck | null>(null);
  const [totalStudentsInPool, setTotalStudentsInPool] = useState(0);

  const [editFormData, setEditFormData] = useState({
    trip_name: '',
    trip_type: 'pickup',
    scheduled_start_time: '07:00',
    scheduled_end_time: '08:00',
    vehicle_id: '',
    driver_id: '',
    attender_id: '',
    start_point: '',
    end_point: '',
  });

  const loadProfileTrips = useCallback(async () => {
    const data = await fetchTripsForProfile(routeProfile.id);
    setProfileTrips(data);
  }, [routeProfile.id, fetchTripsForProfile]);

  // Load total student pool for this route profile (e.g., enrolled students matching the profile criteria)
  const loadStudentPool = useCallback(async () => {
    if (!userSchoolId) return;
    try {
      // Fetch count of all enrolled students in school (in a real system, you'd filter by route profile criteria)
      const { count, error } = await supabase
        .from('students')
        .select('id', { count: 'exact', head: true })
        .eq('school_id', userSchoolId)
        .eq('is_enrolled', true);
      
      if (!error && count !== null) {
        setTotalStudentsInPool(count);
      }
    } catch (err) {
      console.error('Error loading student pool:', err);
    }
  }, [userSchoolId]);

  useEffect(() => {
    let mounted = true;
    const load = async () => {
      setLoading(true);
      const data = await fetchTripsForProfile(routeProfile.id);
      if (mounted) {
        setProfileTrips(data);
        setLoading(false);
      }
    };
    load();
    loadStudentPool();
    return () => { mounted = false; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [routeProfile.id]);

  const loadTripStops = async (trip: TransportTrip) => {
    const stops = await fetchTripStops(trip.id);
    const stopsWithStatus: StopWithStatus[] = stops.map((stop: TripStop) => ({
      ...stop,
      colorStatus: getStopColorStatus(stop),
    }));
    setSelectedTripStops(stopsWithStatus);
  };

  const getStopColorStatus = (stop: TripStop): 'red' | 'yellow' | 'green' => {
    if (stop.assigned_students_count === 0) return 'red';
    if (stop.assigned_students_count >= stop.total_students_at_stop) return 'green';
    return 'yellow';
  };

  const getStopColorClass = (status: 'red' | 'yellow' | 'green') => {
    switch (status) {
      case 'red': return 'bg-red-500';
      case 'yellow': return 'bg-yellow-500';
      case 'green': return 'bg-green-500';
    }
  };

  const getStopColorBadge = (status: 'red' | 'yellow' | 'green') => {
    switch (status) {
      case 'red': return <Badge variant="destructive">Unassigned</Badge>;
      case 'yellow': return <Badge className="bg-yellow-500">Partial</Badge>;
      case 'green': return <Badge className="bg-green-500">Complete</Badge>;
    }
  };

  const handleAutoGenerate = async () => {
    if (!userSchoolId) return;
    
    const result = await autoGenerateTrips(routeProfile.id, userSchoolId, vehicleCapacity, optimizationMode);
    
    if (result && result.tripSuggestions.length > 0) {
      toast.success(`Generated ${result.tripSuggestions.length} trip suggestions (${optimizationMode} optimized)`);
    } else {
      toast.info('No trips generated. Please ensure students are assigned to this route profile.');
    }
  };

  const handleConfirmAutoGenerate = async () => {
    if (!userSchoolId || generatedTrips.length === 0) return;
    
    const success = await createTripsFromSuggestions(
      generatedTrips,
      routeProfile.id,
      userSchoolId,
      'pickup',
      routeProfile.start_time
    );
    
    if (success) {
      setShowAutoGenerateDialog(false);
      setGeneratedTrips([]);
      await loadProfileTrips();
    }
  };

  const handleSelectTrip = async (trip: TransportTrip) => {
    setSelectedTrip(trip);
    await loadTripStops(trip);
  };

  const handleEditTrip = (trip: TransportTrip) => {
    setEditFormData({
      trip_name: trip.trip_name,
      trip_type: trip.trip_type,
      scheduled_start_time: trip.scheduled_start_time,
      scheduled_end_time: trip.scheduled_end_time || '',
      vehicle_id: trip.vehicle_id || '',
      driver_id: trip.driver_id || '',
      attender_id: trip.attender_id || '',
      start_point: trip.start_point || '',
      end_point: trip.end_point || '',
    });
    setSelectedTrip(trip);
    setConflict(null);
    setShowEditTripDialog(true);
  };

  const handleResourceChange = async (resourceType: 'driver' | 'vehicle' | 'attender', resourceId: string) => {
    if (!userSchoolId || !selectedTrip) return;

    setEditFormData(prev => ({ ...prev, [`${resourceType}_id`]: resourceId }));

    // Check for conflicts
    if (resourceId) {
      const conflictResult = await checkResourceConflicts(
        userSchoolId,
        resourceType,
        resourceId,
        editFormData.scheduled_start_time,
        editFormData.scheduled_end_time || editFormData.scheduled_start_time,
        selectedTrip.id
      );
      
      if (conflictResult.hasConflict) {
        setConflict(conflictResult);
      } else {
        setConflict(null);
      }
    } else {
      setConflict(null);
    }
  };

  const handleSaveTrip = async () => {
    if (!selectedTrip || conflict?.hasConflict) {
      if (conflict?.hasConflict) {
        toast.error('Please resolve the conflict before saving');
      }
      return;
    }

    await updateTrip(selectedTrip.id, {
      trip_name: editFormData.trip_name,
      trip_type: editFormData.trip_type,
      scheduled_start_time: editFormData.scheduled_start_time,
      scheduled_end_time: editFormData.scheduled_end_time || null,
      vehicle_id: editFormData.vehicle_id || null,
      driver_id: editFormData.driver_id || null,
      attender_id: editFormData.attender_id || null,
      start_point: editFormData.start_point || null,
      end_point: editFormData.end_point || null,
    });

    setShowEditTripDialog(false);
    await loadProfileTrips();
  };

  const handleDeleteTrip = async (tripId: string) => {
    if (!confirm('Delete this trip and all its stops/assignments?')) return;
    
    await deleteTrip(tripId);
    setSelectedTrip(null);
    setSelectedTripStops([]);
    await loadProfileTrips();
  };

  const getTotalCapacity = () => {
    return profileTrips.reduce((sum, trip) => sum + (trip.vehicle_capacity || 0), 0);
  };

  const getTotalAssigned = () => {
    return profileTrips.reduce((sum, trip) => sum + trip.assigned_students_count, 0);
  };

  const activeVehicles = vehicles.filter(v => v.status === 'active');
  const activeDrivers = drivers.filter(d => d.status === 'active');

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <Loader2 className="h-8 w-8 animate-spin" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header with Profile Info */}
      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Button variant="ghost" size="sm" onClick={onBack}>
                ← Back
              </Button>
              <div>
                <CardTitle className="flex items-center gap-2">
                  <Map className="h-5 w-5" />
                  {routeProfile.profile_name}
                </CardTitle>
                <CardDescription>
                  Trip Planning & Route Optimization
                </CardDescription>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Button 
                variant="outline" 
                onClick={loadProfileTrips}
                size="sm"
              >
                <RefreshCw className="h-4 w-4 mr-2" />
                Refresh
              </Button>
              <Button 
                onClick={() => setShowAutoGenerateDialog(true)}
                className="gap-2"
              >
                <Wand2 className="h-4 w-4" />
                Auto-Generate Trips
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {/* Capacity Overview */}
          <div className="grid grid-cols-5 gap-4 mb-4">
            <div className="text-center p-3 bg-muted rounded-lg">
              <div className="text-2xl font-bold">{profileTrips.length}</div>
              <div className="text-sm text-muted-foreground">Trips</div>
            </div>
            <div className="text-center p-3 bg-muted rounded-lg">
              <div className="text-2xl font-bold">{getTotalAssigned()}</div>
              <div className="text-sm text-muted-foreground">Students Assigned</div>
            </div>
            <div className="text-center p-3 bg-muted rounded-lg">
              <div className={`text-2xl font-bold ${(totalStudentsInPool - getTotalAssigned()) > 0 ? 'text-amber-600' : 'text-green-600'}`}>
                {Math.max(0, totalStudentsInPool - getTotalAssigned())}
              </div>
              <div className="text-sm text-muted-foreground">Unassigned Pool</div>
            </div>
            <div className="text-center p-3 bg-muted rounded-lg">
              <div className="text-2xl font-bold">{getTotalCapacity()}</div>
              <div className="text-sm text-muted-foreground">Total Capacity</div>
            </div>
            <div className="text-center p-3 bg-muted rounded-lg">
              <div className="text-2xl font-bold">
                {getTotalCapacity() > 0 
                  ? `${Math.round((getTotalAssigned() / getTotalCapacity()) * 100)}%`
                  : '0%'
                }
              </div>
              <div className="text-sm text-muted-foreground">Utilization</div>
            </div>
          </div>

          {/* Live Capacity Counter */}
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span>Capacity Utilization</span>
              <span>{getTotalAssigned()} / {getTotalCapacity() || 'No vehicles assigned'}</span>
            </div>
            <Progress 
              value={getTotalCapacity() > 0 ? (getTotalAssigned() / getTotalCapacity()) * 100 : 0} 
              className="h-2"
            />
          </div>
        </CardContent>
      </Card>

      {/* Main Content - Trips List and Map View */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Trips List */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <Bus className="h-5 w-5" />
              Trips ({profileTrips.length})
            </CardTitle>
          </CardHeader>
          <CardContent>
            {profileTrips.length === 0 ? (
              <div className="text-center py-8 text-muted-foreground">
                <Bus className="h-12 w-12 mx-auto mb-4 opacity-50" />
                <p>No trips created yet</p>
                <p className="text-sm mt-2">
                  Click "Auto-Generate Trips" to create trips based on student locations
                </p>
              </div>
            ) : (
              <ScrollArea className="h-[400px]">
                <div className="space-y-3">
                  {profileTrips.map((trip) => (
                    <div
                      key={trip.id}
                      className={`p-4 border rounded-lg cursor-pointer transition-colors ${
                        selectedTrip?.id === trip.id 
                          ? 'border-primary bg-primary/5' 
                          : 'hover:bg-muted/50'
                      }`}
                      onClick={() => handleSelectTrip(trip)}
                    >
                      <div className="flex items-center justify-between mb-2">
                        <div className="font-medium">{trip.trip_name}</div>
                        <div className="flex items-center gap-2">
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={(e) => {
                              e.stopPropagation();
                              handleEditTrip(trip);
                            }}
                          >
                            <Edit2 className="h-4 w-4" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={(e) => {
                              e.stopPropagation();
                              handleDeleteTrip(trip.id);
                            }}
                          >
                            <Trash2 className="h-4 w-4 text-destructive" />
                          </Button>
                        </div>
                      </div>
                      
                      <div className="flex items-center gap-4 text-sm text-muted-foreground flex-wrap">
                        <div className="flex items-center gap-1">
                          <Clock className="h-3 w-3" />
                          {trip.scheduled_start_time}
                        </div>
                        <div className="flex items-center gap-1">
                          <Users className="h-3 w-3" />
                          {trip.assigned_students_count} / {trip.vehicle_capacity || '?'}
                        </div>
                        {trip.estimated_distance_km && (
                          <div className="flex items-center gap-1">
                            <Route className="h-3 w-3" />
                            {trip.estimated_distance_km} km
                          </div>
                        )}
                        <Badge variant="outline">{trip.trip_type}</Badge>
                      </div>
                      
                      {/* Capacity Bar with warning color if over */}
                      <div className="mt-2">
                        <Progress 
                          value={trip.vehicle_capacity 
                            ? Math.min((trip.assigned_students_count / trip.vehicle_capacity) * 100, 100)
                            : 0
                          } 
                          className={`h-1.5 ${
                            trip.vehicle_capacity && trip.assigned_students_count > trip.vehicle_capacity 
                              ? '[&>div]:bg-destructive' 
                              : ''
                          }`}
                        />
                      </div>

                      {/* Over capacity warning */}
                      {trip.vehicle_capacity && trip.assigned_students_count > trip.vehicle_capacity && (
                        <div className="mt-1.5 flex items-center gap-1 text-xs text-destructive">
                          <AlertTriangle className="h-3 w-3" />
                          Over capacity by {trip.assigned_students_count - trip.vehicle_capacity} students
                        </div>
                      )}

                      {/* Resource Assignment Status */}
                      <div className="mt-2 flex gap-2 text-xs flex-wrap">
                        {trip.vehicle ? (
                          <Badge variant="secondary" className="gap-1">
                            <Bus className="h-3 w-3" />
                            {trip.vehicle.vehicle_number}
                          </Badge>
                        ) : (
                          <Badge variant="outline" className="text-muted-foreground">No vehicle</Badge>
                        )}
                        {trip.driver ? (
                          <Badge variant="secondary" className="gap-1">
                            {trip.driver.first_name}
                          </Badge>
                        ) : (
                          <Badge variant="outline" className="text-muted-foreground">No driver</Badge>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </ScrollArea>
            )}
          </CardContent>
        </Card>

        {/* Trip Details / Stop View */}
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-lg flex items-center gap-2">
              <MapPin className="h-5 w-5" />
              {selectedTrip ? `${selectedTrip.trip_name}` : 'Select a Trip'}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {!selectedTrip ? (
              <div className="text-center py-8 text-muted-foreground">
                <MapPin className="h-12 w-12 mx-auto mb-4 opacity-50" />
                <p>Select a trip to view and manage stops</p>
              </div>
            ) : (
              <Tabs defaultValue="stops" className="w-full">
                <TabsList className="mb-4">
                  <TabsTrigger value="stops" className="gap-1">
                    <ListChecks className="h-4 w-4" /> Stops
                  </TabsTrigger>
                  <TabsTrigger value="map" className="gap-1">
                    <Map className="h-4 w-4" /> Route View
                  </TabsTrigger>
                </TabsList>
                
                <TabsContent value="stops">
                  <StopAssignmentPanel
                    tripId={selectedTrip.id}
                    schoolId={userSchoolId || ''}
                    stops={selectedTripStops}
                    vehicleCapacity={selectedTrip.vehicle_capacity}
                    onStopsUpdated={() => loadTripStops(selectedTrip)}
                    onAddStop={async (stop) => {
                      await addTripStop(stop as any);
                      await loadTripStops(selectedTrip);
                    }}
                    onUpdateStop={async (stopId, updates) => {
                      await updateTripStop(stopId, updates);
                      await loadTripStops(selectedTrip);
                    }}
                    onDeleteStop={async (stopId) => {
                      await deleteTripStop(stopId);
                      await loadTripStops(selectedTrip);
                    }}
                  />
                </TabsContent>
                
                <TabsContent value="map">
                  <TripMapView 
                    stops={selectedTripStops} 
                    tripName={selectedTrip.trip_name}
                  />
                </TabsContent>
              </Tabs>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Auto-Generate Dialog */}
      <Dialog open={showAutoGenerateDialog} onOpenChange={setShowAutoGenerateDialog}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Wand2 className="h-5 w-5" />
              Auto-Generate Trips
            </DialogTitle>
            <DialogDescription>
              Automatically create trips based on student locations, distance optimization, and vehicle capacity
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>Vehicle Capacity</Label>
                <Input
                  type="number"
                  value={vehicleCapacity}
                  onChange={(e) => setVehicleCapacity(parseInt(e.target.value) || 40)}
                  min={10}
                  max={100}
                />
                <p className="text-xs text-muted-foreground mt-1">
                  Maximum students per vehicle
                </p>
              </div>
              <div>
                <Label>Optimization Mode</Label>
                <Select value={optimizationMode} onValueChange={(val) => setOptimizationMode(val as 'distance' | 'time' | 'balanced')}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="distance">Shortest Distance</SelectItem>
                    <SelectItem value="time">Minimum Time</SelectItem>
                    <SelectItem value="balanced">Balanced</SelectItem>
                  </SelectContent>
                </Select>
                <p className="text-xs text-muted-foreground mt-1">
                  Algorithm used for route optimization
                </p>
              </div>
            </div>

            {!isGenerating && generatedTrips.length === 0 && (
              <Button onClick={handleAutoGenerate} className="w-full">
                <Wand2 className="h-4 w-4 mr-2" />
                Generate Trip Suggestions
              </Button>
            )}

            {isGenerating && (
              <div className="flex items-center justify-center py-8">
                <Loader2 className="h-8 w-8 animate-spin mr-3" />
                <span>Analyzing routes and generating trips...</span>
              </div>
            )}

            {generatedTrips.length > 0 && (
              <div className="space-y-3">
                <div className="text-sm font-medium">
                  Generated {generatedTrips.length} Trip Suggestions:
                </div>
                <ScrollArea className="h-[200px]">
                  {generatedTrips.map((trip, index) => (
                    <div key={index} className="p-3 border rounded-lg mb-2">
                      <div className="flex items-center justify-between">
                        <div className="font-medium">{trip.tripName}</div>
                        <Badge>{trip.studentCount} students</Badge>
                      </div>
                      <div className="text-sm text-muted-foreground mt-1">
                        {trip.stops} stops • {trip.estimatedDistance} • {trip.estimatedDuration}
                      </div>
                    </div>
                  ))}
                </ScrollArea>
              </div>
            )}
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => {
              setShowAutoGenerateDialog(false);
              setGeneratedTrips([]);
            }}>
              Cancel
            </Button>
            {generatedTrips.length > 0 && (
              <Button onClick={handleConfirmAutoGenerate}>
                <CheckCircle2 className="h-4 w-4 mr-2" />
                Create {generatedTrips.length} Trips
              </Button>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Edit Trip Dialog */}
      <Dialog open={showEditTripDialog} onOpenChange={setShowEditTripDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit Trip</DialogTitle>
            <DialogDescription>
              Modify trip details and resource assignments
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            <div>
              <Label>Trip Name</Label>
              <Input
                value={editFormData.trip_name}
                onChange={(e) => setEditFormData(prev => ({ ...prev, trip_name: e.target.value }))}
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>Start Time</Label>
                <Input
                  type="time"
                  value={editFormData.scheduled_start_time}
                  onChange={(e) => setEditFormData(prev => ({ ...prev, scheduled_start_time: e.target.value }))}
                />
              </div>
              <div>
                <Label>End Time</Label>
                <Input
                  type="time"
                  value={editFormData.scheduled_end_time}
                  onChange={(e) => setEditFormData(prev => ({ ...prev, scheduled_end_time: e.target.value }))}
                />
              </div>
            </div>

            <div>
              <Label>Vehicle</Label>
              <Select
                value={editFormData.vehicle_id || '__none__'}
                onValueChange={(value) => handleResourceChange('vehicle', value === '__none__' ? '' : value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select vehicle" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="__none__">None</SelectItem>
                  {activeVehicles.map(v => (
                    <SelectItem key={v.id} value={v.id}>
                      {v.vehicle_number} ({v.capacity} seats)
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label>Driver</Label>
              <Select
                value={editFormData.driver_id || '__none__'}
                onValueChange={(value) => handleResourceChange('driver', value === '__none__' ? '' : value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select driver" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="__none__">None</SelectItem>
                  {activeDrivers.map(d => (
                    <SelectItem key={d.id} value={d.id}>
                      {d.first_name} {d.last_name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label>Attender</Label>
              <Select
                value={editFormData.attender_id || '__none__'}
                onValueChange={(value) => handleResourceChange('attender', value === '__none__' ? '' : value)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select attender" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="__none__">None</SelectItem>
                  {activeDrivers.map(d => (
                    <SelectItem key={d.id} value={d.id}>
                      {d.first_name} {d.last_name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Start & End Points */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>Start Point</Label>
                <Input
                  value={editFormData.start_point}
                  onChange={(e) => setEditFormData(prev => ({ ...prev, start_point: e.target.value }))}
                  placeholder="e.g., Main Depot"
                />
              </div>
              <div>
                <Label>End Point</Label>
                <Input
                  value={editFormData.end_point}
                  onChange={(e) => setEditFormData(prev => ({ ...prev, end_point: e.target.value }))}
                  placeholder="e.g., School Campus"
                />
              </div>
            </div>

            {/* Conflict Warning */}
            {conflict?.hasConflict && (
              <div className="p-3 bg-destructive/10 border border-destructive/30 rounded-lg flex items-start gap-2">
                <AlertTriangle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />
                <div>
                  <div className="font-medium text-destructive">Conflict Detected</div>
                  <div className="text-sm text-destructive/80">{conflict.message}</div>
                </div>
              </div>
            )}
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowEditTripDialog(false)}>
              Cancel
            </Button>
            <Button onClick={handleSaveTrip} disabled={conflict?.hasConflict}>
              Save Changes
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};
